### ISSUE TITLE
Both molecules of a dimer not included in LIG_solv.* and LIG_dry.*

### ISSUE THREAD

**Issue by tanoury1** [PodewitzLab/PyConSolv#36]
Hi Radu,
I was testing PyConSolv 1.0.2 using an input.xyz file that contained two molecules of acetate anion.  I was able to add Ca2+ as the counterion, and the orca optimization went as expected for the anion dimer input file.  Each molecule of acetate was recognized as a separate ligand (A and B), however, only ligand A was written to the LIG_solv.* and LIG_dry.* files in the MCPB_setup directory.  Consequently, the subsequent equilibration and simulation steps has 1 acetate anion and 1 Ca2+ cation.  The second acetate anion was not incorporated.  I have attached the orca-optimized (PBE/def2-SVP/D3BJ) structure of the acetate anion dimer incase you need to do some troubleshooting.  (I changed the file type extension to txt.  Just change it back to xyz for your use).

Is this the best way to model two anions and a Ca2+ counterion system?

All the best,
Jerry
[orca_opt.txt](https://github.com/PodewitzLab/PyConSolv/files/13054611/orca_opt.txt)

**Comment by Lapsis-glitch** [comment]
Hi Jerry,
Thanks for reporting this, I was able to reproduce it on my end. The problem lies in the fragment detection algorithm that is implemented, since it presumes that you only have one single solute and not a non-covalently bound complex of multiple structures.
I'll work on getting this fixed.

A workaround that you can do in the meantime is:

1. Convert the "Full_PDB.pdb" structure to mol2 with something like openbabel (obabel -ipdb Full_PDB.pdb -omol2 -O LX.mol2)
2. Copy the partial charges from the multiwfn calculation in the newly created "LX.mol2" file ("orca_opt.molden.chg" in the orca_calculations/opt folder)
3. Copy the correct atom types from "A.mol2" and "B.mol2" in the "LX.mol2" file
4. Modify the "LIG_tleap.in" file as follows:

source oldff/leaprc.ff99SB
source leaprc.gaff
source leaprc.water.tip3p
**A = loadmol2 A.mol2
B = loadmol2 B.mol2
loadamberparams A.frcmod
loadamberparams B.frcmod
LIG = loadmol2 LX.mol2**
savepdb LIG LIG_dry.pdb
addions LIG CA 1
saveamberparm LIG LIG_dry.prmtop LIG_dry.inpcrd
solvatebox LIG TIP3PBOX 20 iso
savepdb LIG LIG_solv.pdb
saveamberparm LIG LIG_solv.prmtop LIG_solv.inpcrd
quit

5. Run "tleap -f LIG_tleap.in" and copy the topology files to the simulation and equilibration folders
6. Copy the "LIG_solv.inpcrd" into the equilibration folder ad "00.rst7"
7. Modify the pyconsolv.restart file so that it contains the word "tleap"
8. Restart pyconsolv and it should start directly with the equilibration

In case you are using a custom solvent, be sure to load the solvent mol2 and frcmod files in the "LIG_tleap.in" file and change the solvatebox command to the solvent of choice.

All the best,
Radu

**Comment by tanoury1** [comment]
Thanks Radu.  I was wondering if I put a "dummy bond" between the two
fragments.  Would they remain "bonded" during the Amber equilibration and
simulation steps?

Jerry

**Comment by Lapsis-glitch** [comment]
Hi Jerey,
You could add a dummy bond, but this might require some changes in the atom paramters. I think a better approach would be setting a restraint on the distance between the residues or atoms. 
Radu

**Comment by Lapsis-glitch** [comment]
Solved with 538412f1cb219ee4e7095a55fe4e3a219ddddcab
